version: '3.8'
services:
  db-mysql:
    image: mysql:5.7.40
    restart: always
    environment:
      - MYSQL_DATABASE=foodash
      - MYSQL_ROOT_PASSWORD=capstone
    ports:
      - "3307:3306"
